// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LOGGER_SANDBOX_SCHEMAS_LOGGER_H_
#define FLATBUFFERS_GENERATED_LOGGER_SANDBOX_SCHEMAS_LOGGER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace sandbox {
namespace schemas {
namespace logger {

struct LogArgs;
struct LogArgsBuilder;
struct LogArgsT;

struct SetPropertyArgs;
struct SetPropertyArgsBuilder;
struct SetPropertyArgsT;

struct GetPropertyArgs;
struct GetPropertyArgsBuilder;
struct GetPropertyArgsT;

enum LoggerCommand : uint32_t {
  LoggerCommand_Log = 1,
  LoggerCommand_SetProperty = 2,
  LoggerCommand_GetProperty = 3,
  LoggerCommand_MIN = LoggerCommand_Log,
  LoggerCommand_MAX = LoggerCommand_GetProperty
};

inline const LoggerCommand (&EnumValuesLoggerCommand())[3] {
  static const LoggerCommand values[] = {
    LoggerCommand_Log,
    LoggerCommand_SetProperty,
    LoggerCommand_GetProperty
  };
  return values;
}

inline const char * const *EnumNamesLoggerCommand() {
  static const char * const names[4] = {
    "Log",
    "SetProperty",
    "GetProperty",
    nullptr
  };
  return names;
}

inline const char *EnumNameLoggerCommand(LoggerCommand e) {
  if (::flatbuffers::IsOutRange(e, LoggerCommand_Log, LoggerCommand_GetProperty)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(LoggerCommand_Log);
  return EnumNamesLoggerCommand()[index];
}

enum LogLevel : int8_t {
  LogLevel_Trace = 0,
  LogLevel_Debug = 1,
  LogLevel_Info = 2,
  LogLevel_Warn = 3,
  LogLevel_Error = 4,
  LogLevel_Fatal = 5,
  LogLevel_MIN = LogLevel_Trace,
  LogLevel_MAX = LogLevel_Fatal
};

inline const LogLevel (&EnumValuesLogLevel())[6] {
  static const LogLevel values[] = {
    LogLevel_Trace,
    LogLevel_Debug,
    LogLevel_Info,
    LogLevel_Warn,
    LogLevel_Error,
    LogLevel_Fatal
  };
  return values;
}

inline const char * const *EnumNamesLogLevel() {
  static const char * const names[7] = {
    "Trace",
    "Debug",
    "Info",
    "Warn",
    "Error",
    "Fatal",
    nullptr
  };
  return names;
}

inline const char *EnumNameLogLevel(LogLevel e) {
  if (::flatbuffers::IsOutRange(e, LogLevel_Trace, LogLevel_Fatal)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLogLevel()[index];
}

struct LogArgsT : public ::flatbuffers::NativeTable {
  typedef LogArgs TableType;
  sandbox::schemas::logger::LogLevel level = sandbox::schemas::logger::LogLevel_Info;
  std::string message{};
  std::string source_file{};
  int32_t source_line = 0;
  bool throw_on_error = false;
  uint64_t out_result_ptr = 0;
};

struct LogArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LogArgsT NativeTableType;
  typedef LogArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LEVEL = 4,
    VT_MESSAGE = 6,
    VT_SOURCE_FILE = 8,
    VT_SOURCE_LINE = 10,
    VT_THROW_ON_ERROR = 12,
    VT_OUT_RESULT_PTR = 14
  };
  sandbox::schemas::logger::LogLevel level() const {
    return static_cast<sandbox::schemas::logger::LogLevel>(GetField<int8_t>(VT_LEVEL, 2));
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  const ::flatbuffers::String *source_file() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_FILE);
  }
  int32_t source_line() const {
    return GetField<int32_t>(VT_SOURCE_LINE, 0);
  }
  bool throw_on_error() const {
    return GetField<uint8_t>(VT_THROW_ON_ERROR, 0) != 0;
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_LEVEL, 1) &&
           VerifyOffsetRequired(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyOffset(verifier, VT_SOURCE_FILE) &&
           verifier.VerifyString(source_file()) &&
           VerifyField<int32_t>(verifier, VT_SOURCE_LINE, 4) &&
           VerifyField<uint8_t>(verifier, VT_THROW_ON_ERROR, 1) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  LogArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(LogArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<LogArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LogArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct LogArgsBuilder {
  typedef LogArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_level(sandbox::schemas::logger::LogLevel level) {
    fbb_.AddElement<int8_t>(LogArgs::VT_LEVEL, static_cast<int8_t>(level), 2);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(LogArgs::VT_MESSAGE, message);
  }
  void add_source_file(::flatbuffers::Offset<::flatbuffers::String> source_file) {
    fbb_.AddOffset(LogArgs::VT_SOURCE_FILE, source_file);
  }
  void add_source_line(int32_t source_line) {
    fbb_.AddElement<int32_t>(LogArgs::VT_SOURCE_LINE, source_line, 0);
  }
  void add_throw_on_error(bool throw_on_error) {
    fbb_.AddElement<uint8_t>(LogArgs::VT_THROW_ON_ERROR, static_cast<uint8_t>(throw_on_error), 0);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(LogArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit LogArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LogArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LogArgs>(end);
    fbb_.Required(o, LogArgs::VT_MESSAGE);
    return o;
  }
};

inline ::flatbuffers::Offset<LogArgs> CreateLogArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    sandbox::schemas::logger::LogLevel level = sandbox::schemas::logger::LogLevel_Info,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source_file = 0,
    int32_t source_line = 0,
    bool throw_on_error = false,
    uint64_t out_result_ptr = 0) {
  LogArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_source_line(source_line);
  builder_.add_source_file(source_file);
  builder_.add_message(message);
  builder_.add_throw_on_error(throw_on_error);
  builder_.add_level(level);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LogArgs> CreateLogArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    sandbox::schemas::logger::LogLevel level = sandbox::schemas::logger::LogLevel_Info,
    const char *message = nullptr,
    const char *source_file = nullptr,
    int32_t source_line = 0,
    bool throw_on_error = false,
    uint64_t out_result_ptr = 0) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  auto source_file__ = source_file ? _fbb.CreateString(source_file) : 0;
  return sandbox::schemas::logger::CreateLogArgs(
      _fbb,
      level,
      message__,
      source_file__,
      source_line,
      throw_on_error,
      out_result_ptr);
}

::flatbuffers::Offset<LogArgs> CreateLogArgs(::flatbuffers::FlatBufferBuilder &_fbb, const LogArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SetPropertyArgsT : public ::flatbuffers::NativeTable {
  typedef SetPropertyArgs TableType;
  std::string key{};
  std::string json_value{};
};

struct SetPropertyArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetPropertyArgsT NativeTableType;
  typedef SetPropertyArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_JSON_VALUE = 6
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  const ::flatbuffers::String *json_value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_JSON_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyOffset(verifier, VT_JSON_VALUE) &&
           verifier.VerifyString(json_value()) &&
           verifier.EndTable();
  }
  SetPropertyArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SetPropertyArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SetPropertyArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetPropertyArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SetPropertyArgsBuilder {
  typedef SetPropertyArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(SetPropertyArgs::VT_KEY, key);
  }
  void add_json_value(::flatbuffers::Offset<::flatbuffers::String> json_value) {
    fbb_.AddOffset(SetPropertyArgs::VT_JSON_VALUE, json_value);
  }
  explicit SetPropertyArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetPropertyArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetPropertyArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetPropertyArgs> CreateSetPropertyArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    ::flatbuffers::Offset<::flatbuffers::String> json_value = 0) {
  SetPropertyArgsBuilder builder_(_fbb);
  builder_.add_json_value(json_value);
  builder_.add_key(key);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetPropertyArgs> CreateSetPropertyArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    const char *json_value = nullptr) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  auto json_value__ = json_value ? _fbb.CreateString(json_value) : 0;
  return sandbox::schemas::logger::CreateSetPropertyArgs(
      _fbb,
      key__,
      json_value__);
}

::flatbuffers::Offset<SetPropertyArgs> CreateSetPropertyArgs(::flatbuffers::FlatBufferBuilder &_fbb, const SetPropertyArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct GetPropertyArgsT : public ::flatbuffers::NativeTable {
  typedef GetPropertyArgs TableType;
  std::string key{};
  uint64_t out_payload_ptr = 0;
  uint64_t out_result_ptr = 0;
};

struct GetPropertyArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GetPropertyArgsT NativeTableType;
  typedef GetPropertyArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_OUT_PAYLOAD_PTR = 6,
    VT_OUT_RESULT_PTR = 8
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  uint64_t out_payload_ptr() const {
    return GetField<uint64_t>(VT_OUT_PAYLOAD_PTR, 0);
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyField<uint64_t>(verifier, VT_OUT_PAYLOAD_PTR, 8) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  GetPropertyArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(GetPropertyArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<GetPropertyArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GetPropertyArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct GetPropertyArgsBuilder {
  typedef GetPropertyArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(GetPropertyArgs::VT_KEY, key);
  }
  void add_out_payload_ptr(uint64_t out_payload_ptr) {
    fbb_.AddElement<uint64_t>(GetPropertyArgs::VT_OUT_PAYLOAD_PTR, out_payload_ptr, 0);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(GetPropertyArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit GetPropertyArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GetPropertyArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GetPropertyArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GetPropertyArgs> CreateGetPropertyArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    uint64_t out_payload_ptr = 0,
    uint64_t out_result_ptr = 0) {
  GetPropertyArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_out_payload_ptr(out_payload_ptr);
  builder_.add_key(key);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GetPropertyArgs> CreateGetPropertyArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    uint64_t out_payload_ptr = 0,
    uint64_t out_result_ptr = 0) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  return sandbox::schemas::logger::CreateGetPropertyArgs(
      _fbb,
      key__,
      out_payload_ptr,
      out_result_ptr);
}

::flatbuffers::Offset<GetPropertyArgs> CreateGetPropertyArgs(::flatbuffers::FlatBufferBuilder &_fbb, const GetPropertyArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline LogArgsT *LogArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<LogArgsT>(new LogArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void LogArgs::UnPackTo(LogArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = level(); _o->level = _e; }
  { auto _e = message(); if (_e) _o->message = _e->str(); }
  { auto _e = source_file(); if (_e) _o->source_file = _e->str(); }
  { auto _e = source_line(); _o->source_line = _e; }
  { auto _e = throw_on_error(); _o->throw_on_error = _e; }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<LogArgs> LogArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LogArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateLogArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<LogArgs> CreateLogArgs(::flatbuffers::FlatBufferBuilder &_fbb, const LogArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const LogArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _level = _o->level;
  auto _message = _fbb.CreateString(_o->message);
  auto _source_file = _o->source_file.empty() ? 0 : _fbb.CreateString(_o->source_file);
  auto _source_line = _o->source_line;
  auto _throw_on_error = _o->throw_on_error;
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::logger::CreateLogArgs(
      _fbb,
      _level,
      _message,
      _source_file,
      _source_line,
      _throw_on_error,
      _out_result_ptr);
}

inline SetPropertyArgsT *SetPropertyArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SetPropertyArgsT>(new SetPropertyArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SetPropertyArgs::UnPackTo(SetPropertyArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = key(); if (_e) _o->key = _e->str(); }
  { auto _e = json_value(); if (_e) _o->json_value = _e->str(); }
}

inline ::flatbuffers::Offset<SetPropertyArgs> SetPropertyArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetPropertyArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSetPropertyArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SetPropertyArgs> CreateSetPropertyArgs(::flatbuffers::FlatBufferBuilder &_fbb, const SetPropertyArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SetPropertyArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _key = _o->key.empty() ? 0 : _fbb.CreateString(_o->key);
  auto _json_value = _o->json_value.empty() ? 0 : _fbb.CreateString(_o->json_value);
  return sandbox::schemas::logger::CreateSetPropertyArgs(
      _fbb,
      _key,
      _json_value);
}

inline GetPropertyArgsT *GetPropertyArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<GetPropertyArgsT>(new GetPropertyArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void GetPropertyArgs::UnPackTo(GetPropertyArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = key(); if (_e) _o->key = _e->str(); }
  { auto _e = out_payload_ptr(); _o->out_payload_ptr = _e; }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<GetPropertyArgs> GetPropertyArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GetPropertyArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateGetPropertyArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<GetPropertyArgs> CreateGetPropertyArgs(::flatbuffers::FlatBufferBuilder &_fbb, const GetPropertyArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const GetPropertyArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _key = _o->key.empty() ? 0 : _fbb.CreateString(_o->key);
  auto _out_payload_ptr = _o->out_payload_ptr;
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::logger::CreateGetPropertyArgs(
      _fbb,
      _key,
      _out_payload_ptr,
      _out_result_ptr);
}

inline const sandbox::schemas::logger::LogArgs *GetLogArgs(const void *buf) {
  return ::flatbuffers::GetRoot<sandbox::schemas::logger::LogArgs>(buf);
}

inline const sandbox::schemas::logger::LogArgs *GetSizePrefixedLogArgs(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<sandbox::schemas::logger::LogArgs>(buf);
}

inline bool VerifyLogArgsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<sandbox::schemas::logger::LogArgs>(nullptr);
}

inline bool VerifySizePrefixedLogArgsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<sandbox::schemas::logger::LogArgs>(nullptr);
}

inline void FinishLogArgsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<sandbox::schemas::logger::LogArgs> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedLogArgsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<sandbox::schemas::logger::LogArgs> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<sandbox::schemas::logger::LogArgsT> UnPackLogArgs(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<sandbox::schemas::logger::LogArgsT>(GetLogArgs(buf)->UnPack(res));
}

inline std::unique_ptr<sandbox::schemas::logger::LogArgsT> UnPackSizePrefixedLogArgs(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<sandbox::schemas::logger::LogArgsT>(GetSizePrefixedLogArgs(buf)->UnPack(res));
}

}  // namespace logger
}  // namespace schemas
}  // namespace sandbox

#endif  // FLATBUFFERS_GENERATED_LOGGER_SANDBOX_SCHEMAS_LOGGER_H_
