// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RUNNER_SANDBOX_SCHEMAS_RUNNER_H_
#define FLATBUFFERS_GENERATED_RUNNER_SANDBOX_SCHEMAS_RUNNER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace sandbox {
namespace schemas {
namespace runner {

struct StartAsyncArgs;
struct StartAsyncArgsBuilder;
struct StartAsyncArgsT;

struct RunSyncArgs;
struct RunSyncArgsBuilder;
struct RunSyncArgsT;

struct QuitArgs;
struct QuitArgsBuilder;
struct QuitArgsT;

struct PauseArgs;
struct PauseArgsBuilder;
struct PauseArgsT;

struct ResumeArgs;
struct ResumeArgsBuilder;
struct ResumeArgsT;

struct SetPropertyArgs;
struct SetPropertyArgsBuilder;
struct SetPropertyArgsT;

struct GetPropertyArgs;
struct GetPropertyArgsBuilder;
struct GetPropertyArgsT;

enum RunnerCommand : uint32_t {
  RunnerCommand_StartAsync = 1,
  RunnerCommand_RunSync = 2,
  RunnerCommand_Quit = 3,
  RunnerCommand_Pause = 4,
  RunnerCommand_Resume = 5,
  RunnerCommand_SetProperty = 6,
  RunnerCommand_GetProperty = 7,
  RunnerCommand_MIN = RunnerCommand_StartAsync,
  RunnerCommand_MAX = RunnerCommand_GetProperty
};

inline const RunnerCommand (&EnumValuesRunnerCommand())[7] {
  static const RunnerCommand values[] = {
    RunnerCommand_StartAsync,
    RunnerCommand_RunSync,
    RunnerCommand_Quit,
    RunnerCommand_Pause,
    RunnerCommand_Resume,
    RunnerCommand_SetProperty,
    RunnerCommand_GetProperty
  };
  return values;
}

inline const char * const *EnumNamesRunnerCommand() {
  static const char * const names[8] = {
    "StartAsync",
    "RunSync",
    "Quit",
    "Pause",
    "Resume",
    "SetProperty",
    "GetProperty",
    nullptr
  };
  return names;
}

inline const char *EnumNameRunnerCommand(RunnerCommand e) {
  if (::flatbuffers::IsOutRange(e, RunnerCommand_StartAsync, RunnerCommand_GetProperty)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(RunnerCommand_StartAsync);
  return EnumNamesRunnerCommand()[index];
}

struct StartAsyncArgsT : public ::flatbuffers::NativeTable {
  typedef StartAsyncArgs TableType;
  uint64_t ecs_world_ptr = 0;
  uint64_t out_result_ptr = 0;
};

struct StartAsyncArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StartAsyncArgsT NativeTableType;
  typedef StartAsyncArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ECS_WORLD_PTR = 4,
    VT_OUT_RESULT_PTR = 6
  };
  uint64_t ecs_world_ptr() const {
    return GetField<uint64_t>(VT_ECS_WORLD_PTR, 0);
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ECS_WORLD_PTR, 8) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  StartAsyncArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(StartAsyncArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<StartAsyncArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const StartAsyncArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct StartAsyncArgsBuilder {
  typedef StartAsyncArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ecs_world_ptr(uint64_t ecs_world_ptr) {
    fbb_.AddElement<uint64_t>(StartAsyncArgs::VT_ECS_WORLD_PTR, ecs_world_ptr, 0);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(StartAsyncArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit StartAsyncArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StartAsyncArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StartAsyncArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StartAsyncArgs> CreateStartAsyncArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t ecs_world_ptr = 0,
    uint64_t out_result_ptr = 0) {
  StartAsyncArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_ecs_world_ptr(ecs_world_ptr);
  return builder_.Finish();
}

::flatbuffers::Offset<StartAsyncArgs> CreateStartAsyncArgs(::flatbuffers::FlatBufferBuilder &_fbb, const StartAsyncArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct RunSyncArgsT : public ::flatbuffers::NativeTable {
  typedef RunSyncArgs TableType;
  uint64_t ecs_world_ptr = 0;
  uint64_t out_result_ptr = 0;
};

struct RunSyncArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RunSyncArgsT NativeTableType;
  typedef RunSyncArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ECS_WORLD_PTR = 4,
    VT_OUT_RESULT_PTR = 6
  };
  uint64_t ecs_world_ptr() const {
    return GetField<uint64_t>(VT_ECS_WORLD_PTR, 0);
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ECS_WORLD_PTR, 8) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  RunSyncArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RunSyncArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<RunSyncArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RunSyncArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct RunSyncArgsBuilder {
  typedef RunSyncArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ecs_world_ptr(uint64_t ecs_world_ptr) {
    fbb_.AddElement<uint64_t>(RunSyncArgs::VT_ECS_WORLD_PTR, ecs_world_ptr, 0);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(RunSyncArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit RunSyncArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RunSyncArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RunSyncArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RunSyncArgs> CreateRunSyncArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t ecs_world_ptr = 0,
    uint64_t out_result_ptr = 0) {
  RunSyncArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_ecs_world_ptr(ecs_world_ptr);
  return builder_.Finish();
}

::flatbuffers::Offset<RunSyncArgs> CreateRunSyncArgs(::flatbuffers::FlatBufferBuilder &_fbb, const RunSyncArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct QuitArgsT : public ::flatbuffers::NativeTable {
  typedef QuitArgs TableType;
  uint64_t out_result_ptr = 0;
};

struct QuitArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef QuitArgsT NativeTableType;
  typedef QuitArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OUT_RESULT_PTR = 4
  };
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  QuitArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(QuitArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<QuitArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const QuitArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct QuitArgsBuilder {
  typedef QuitArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(QuitArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit QuitArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<QuitArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<QuitArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<QuitArgs> CreateQuitArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t out_result_ptr = 0) {
  QuitArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  return builder_.Finish();
}

::flatbuffers::Offset<QuitArgs> CreateQuitArgs(::flatbuffers::FlatBufferBuilder &_fbb, const QuitArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct PauseArgsT : public ::flatbuffers::NativeTable {
  typedef PauseArgs TableType;
  uint64_t out_result_ptr = 0;
};

struct PauseArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PauseArgsT NativeTableType;
  typedef PauseArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OUT_RESULT_PTR = 4
  };
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  PauseArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PauseArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<PauseArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PauseArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PauseArgsBuilder {
  typedef PauseArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(PauseArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit PauseArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PauseArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PauseArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PauseArgs> CreatePauseArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t out_result_ptr = 0) {
  PauseArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  return builder_.Finish();
}

::flatbuffers::Offset<PauseArgs> CreatePauseArgs(::flatbuffers::FlatBufferBuilder &_fbb, const PauseArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ResumeArgsT : public ::flatbuffers::NativeTable {
  typedef ResumeArgs TableType;
  uint64_t out_result_ptr = 0;
};

struct ResumeArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ResumeArgsT NativeTableType;
  typedef ResumeArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OUT_RESULT_PTR = 4
  };
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  ResumeArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ResumeArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ResumeArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ResumeArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ResumeArgsBuilder {
  typedef ResumeArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(ResumeArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit ResumeArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ResumeArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ResumeArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ResumeArgs> CreateResumeArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t out_result_ptr = 0) {
  ResumeArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  return builder_.Finish();
}

::flatbuffers::Offset<ResumeArgs> CreateResumeArgs(::flatbuffers::FlatBufferBuilder &_fbb, const ResumeArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SetPropertyArgsT : public ::flatbuffers::NativeTable {
  typedef SetPropertyArgs TableType;
  std::string key{};
  std::string json_value{};
};

struct SetPropertyArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetPropertyArgsT NativeTableType;
  typedef SetPropertyArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_JSON_VALUE = 6
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  const ::flatbuffers::String *json_value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_JSON_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyOffset(verifier, VT_JSON_VALUE) &&
           verifier.VerifyString(json_value()) &&
           verifier.EndTable();
  }
  SetPropertyArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SetPropertyArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SetPropertyArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetPropertyArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SetPropertyArgsBuilder {
  typedef SetPropertyArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(SetPropertyArgs::VT_KEY, key);
  }
  void add_json_value(::flatbuffers::Offset<::flatbuffers::String> json_value) {
    fbb_.AddOffset(SetPropertyArgs::VT_JSON_VALUE, json_value);
  }
  explicit SetPropertyArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetPropertyArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetPropertyArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetPropertyArgs> CreateSetPropertyArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    ::flatbuffers::Offset<::flatbuffers::String> json_value = 0) {
  SetPropertyArgsBuilder builder_(_fbb);
  builder_.add_json_value(json_value);
  builder_.add_key(key);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetPropertyArgs> CreateSetPropertyArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    const char *json_value = nullptr) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  auto json_value__ = json_value ? _fbb.CreateString(json_value) : 0;
  return sandbox::schemas::runner::CreateSetPropertyArgs(
      _fbb,
      key__,
      json_value__);
}

::flatbuffers::Offset<SetPropertyArgs> CreateSetPropertyArgs(::flatbuffers::FlatBufferBuilder &_fbb, const SetPropertyArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct GetPropertyArgsT : public ::flatbuffers::NativeTable {
  typedef GetPropertyArgs TableType;
  std::string key{};
  uint64_t out_payload_ptr = 0;
  uint64_t out_result_ptr = 0;
};

struct GetPropertyArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GetPropertyArgsT NativeTableType;
  typedef GetPropertyArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_OUT_PAYLOAD_PTR = 6,
    VT_OUT_RESULT_PTR = 8
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  uint64_t out_payload_ptr() const {
    return GetField<uint64_t>(VT_OUT_PAYLOAD_PTR, 0);
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyField<uint64_t>(verifier, VT_OUT_PAYLOAD_PTR, 8) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  GetPropertyArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(GetPropertyArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<GetPropertyArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GetPropertyArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct GetPropertyArgsBuilder {
  typedef GetPropertyArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(GetPropertyArgs::VT_KEY, key);
  }
  void add_out_payload_ptr(uint64_t out_payload_ptr) {
    fbb_.AddElement<uint64_t>(GetPropertyArgs::VT_OUT_PAYLOAD_PTR, out_payload_ptr, 0);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(GetPropertyArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit GetPropertyArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GetPropertyArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GetPropertyArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GetPropertyArgs> CreateGetPropertyArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    uint64_t out_payload_ptr = 0,
    uint64_t out_result_ptr = 0) {
  GetPropertyArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_out_payload_ptr(out_payload_ptr);
  builder_.add_key(key);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GetPropertyArgs> CreateGetPropertyArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    uint64_t out_payload_ptr = 0,
    uint64_t out_result_ptr = 0) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  return sandbox::schemas::runner::CreateGetPropertyArgs(
      _fbb,
      key__,
      out_payload_ptr,
      out_result_ptr);
}

::flatbuffers::Offset<GetPropertyArgs> CreateGetPropertyArgs(::flatbuffers::FlatBufferBuilder &_fbb, const GetPropertyArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline StartAsyncArgsT *StartAsyncArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<StartAsyncArgsT>(new StartAsyncArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void StartAsyncArgs::UnPackTo(StartAsyncArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = ecs_world_ptr(); _o->ecs_world_ptr = _e; }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<StartAsyncArgs> StartAsyncArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const StartAsyncArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateStartAsyncArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<StartAsyncArgs> CreateStartAsyncArgs(::flatbuffers::FlatBufferBuilder &_fbb, const StartAsyncArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const StartAsyncArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _ecs_world_ptr = _o->ecs_world_ptr;
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::runner::CreateStartAsyncArgs(
      _fbb,
      _ecs_world_ptr,
      _out_result_ptr);
}

inline RunSyncArgsT *RunSyncArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RunSyncArgsT>(new RunSyncArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void RunSyncArgs::UnPackTo(RunSyncArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = ecs_world_ptr(); _o->ecs_world_ptr = _e; }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<RunSyncArgs> RunSyncArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RunSyncArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateRunSyncArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<RunSyncArgs> CreateRunSyncArgs(::flatbuffers::FlatBufferBuilder &_fbb, const RunSyncArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const RunSyncArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _ecs_world_ptr = _o->ecs_world_ptr;
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::runner::CreateRunSyncArgs(
      _fbb,
      _ecs_world_ptr,
      _out_result_ptr);
}

inline QuitArgsT *QuitArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<QuitArgsT>(new QuitArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void QuitArgs::UnPackTo(QuitArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<QuitArgs> QuitArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const QuitArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateQuitArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<QuitArgs> CreateQuitArgs(::flatbuffers::FlatBufferBuilder &_fbb, const QuitArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const QuitArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::runner::CreateQuitArgs(
      _fbb,
      _out_result_ptr);
}

inline PauseArgsT *PauseArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<PauseArgsT>(new PauseArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void PauseArgs::UnPackTo(PauseArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<PauseArgs> PauseArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PauseArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreatePauseArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<PauseArgs> CreatePauseArgs(::flatbuffers::FlatBufferBuilder &_fbb, const PauseArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PauseArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::runner::CreatePauseArgs(
      _fbb,
      _out_result_ptr);
}

inline ResumeArgsT *ResumeArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ResumeArgsT>(new ResumeArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ResumeArgs::UnPackTo(ResumeArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<ResumeArgs> ResumeArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ResumeArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateResumeArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ResumeArgs> CreateResumeArgs(::flatbuffers::FlatBufferBuilder &_fbb, const ResumeArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ResumeArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::runner::CreateResumeArgs(
      _fbb,
      _out_result_ptr);
}

inline SetPropertyArgsT *SetPropertyArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SetPropertyArgsT>(new SetPropertyArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SetPropertyArgs::UnPackTo(SetPropertyArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = key(); if (_e) _o->key = _e->str(); }
  { auto _e = json_value(); if (_e) _o->json_value = _e->str(); }
}

inline ::flatbuffers::Offset<SetPropertyArgs> SetPropertyArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetPropertyArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSetPropertyArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SetPropertyArgs> CreateSetPropertyArgs(::flatbuffers::FlatBufferBuilder &_fbb, const SetPropertyArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SetPropertyArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _key = _o->key.empty() ? 0 : _fbb.CreateString(_o->key);
  auto _json_value = _o->json_value.empty() ? 0 : _fbb.CreateString(_o->json_value);
  return sandbox::schemas::runner::CreateSetPropertyArgs(
      _fbb,
      _key,
      _json_value);
}

inline GetPropertyArgsT *GetPropertyArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<GetPropertyArgsT>(new GetPropertyArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void GetPropertyArgs::UnPackTo(GetPropertyArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = key(); if (_e) _o->key = _e->str(); }
  { auto _e = out_payload_ptr(); _o->out_payload_ptr = _e; }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<GetPropertyArgs> GetPropertyArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GetPropertyArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateGetPropertyArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<GetPropertyArgs> CreateGetPropertyArgs(::flatbuffers::FlatBufferBuilder &_fbb, const GetPropertyArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const GetPropertyArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _key = _o->key.empty() ? 0 : _fbb.CreateString(_o->key);
  auto _out_payload_ptr = _o->out_payload_ptr;
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::runner::CreateGetPropertyArgs(
      _fbb,
      _key,
      _out_payload_ptr,
      _out_result_ptr);
}

}  // namespace runner
}  // namespace schemas
}  // namespace sandbox

#endif  // FLATBUFFERS_GENERATED_RUNNER_SANDBOX_SCHEMAS_RUNNER_H_
