namespace sandbox.schemas.logger;

enum LoggerCommand : uint {
    Log = 1,
    SetProperty = 2,
    GetProperty = 3
}

enum LogLevel : byte { Trace = 0, Debug, Info, Warn, Error, Fatal }

table LogArgs {
    level: LogLevel = Info;
    message: string (required);
    source_file: string;
    source_line: int;
    throw_on_error: bool = false;
    out_result_ptr: uint64; // cast to int32_t*
}

table SetPropertyArgs {
    key: string;
    json_value: string;
}

table GetPropertyArgs {
    key: string;
    out_payload_ptr: uint64; // cast to sandbox_payload*
    out_result_ptr: uint64; // cast to int32_t*
}

root_type LogArgs;
