namespace sandbox.schemas.runner;

enum RunnerCommand : uint {
    StartAsync = 1,
    RunSync = 2,
    Quit = 3,
    Pause = 4,
    Resume = 5,
    SetProperty = 6,
    GetProperty = 7
}

table StartAsyncArgs {
    ecs_world_ptr: uint64; // cast to flecs::world*
    out_result_ptr: uint64; // cast to int32_t*
}

table RunSyncArgs {
    ecs_world_ptr: uint64; // cast to flecs::world*
    out_result_ptr: uint64; // cast to int32_t*
}

table QuitArgs {
    out_result_ptr: uint64; // cast to int32_t*
}

table PauseArgs {
    out_result_ptr: uint64; // cast to int32_t*
}

table ResumeArgs {
    out_result_ptr: uint64; // cast to int32_t*
}

table SetPropertyArgs {
    key: string;
    json_value: string;
}

table GetPropertyArgs {
    key: string;
    out_payload_ptr: uint64; // cast to sandbox_payload*
    out_result_ptr: uint64; // cast to int32_t*
}
