// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FILESYSTEM_SANDBOX_SCHEMAS_FILESYSTEM_H_
#define FLATBUFFERS_GENERATED_FILESYSTEM_SANDBOX_SCHEMAS_FILESYSTEM_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace sandbox {
namespace schemas {
namespace filesystem {

struct StringList;
struct StringListBuilder;
struct StringListT;

struct FileMetadata;
struct FileMetadataBuilder;
struct FileMetadataT;

struct MountArgs;
struct MountArgsBuilder;
struct MountArgsT;

struct UnmountArgs;
struct UnmountArgsBuilder;
struct UnmountArgsT;

struct ReadArgs;
struct ReadArgsBuilder;
struct ReadArgsT;

struct WriteArgs;
struct WriteArgsBuilder;
struct WriteArgsT;

struct ListArgs;
struct ListArgsBuilder;
struct ListArgsT;

struct RemoveArgs;
struct RemoveArgsBuilder;
struct RemoveArgsT;

struct MkdirArgs;
struct MkdirArgsBuilder;
struct MkdirArgsT;

struct RenameArgs;
struct RenameArgsBuilder;
struct RenameArgsT;

struct CopyArgs;
struct CopyArgsBuilder;
struct CopyArgsT;

struct MoveArgs;
struct MoveArgsBuilder;
struct MoveArgsT;

struct StateArgs;
struct StateArgsBuilder;
struct StateArgsT;

struct AbsoluteArgs;
struct AbsoluteArgsBuilder;
struct AbsoluteArgsT;

struct SetPropertyArgs;
struct SetPropertyArgsBuilder;
struct SetPropertyArgsT;

struct GetPropertyArgs;
struct GetPropertyArgsBuilder;
struct GetPropertyArgsT;

enum FilesystemCommand : uint32_t {
  FilesystemCommand_Mount = 1,
  FilesystemCommand_Unmount = 2,
  FilesystemCommand_Read = 3,
  FilesystemCommand_Write = 4,
  FilesystemCommand_List = 5,
  FilesystemCommand_Remove = 6,
  FilesystemCommand_Mkdir = 7,
  FilesystemCommand_Rename = 8,
  FilesystemCommand_Copy = 9,
  FilesystemCommand_Move = 10,
  FilesystemCommand_State = 11,
  FilesystemCommand_Absolute = 12,
  FilesystemCommand_SetProperty = 13,
  FilesystemCommand_GetProperty = 14,
  FilesystemCommand_MIN = FilesystemCommand_Mount,
  FilesystemCommand_MAX = FilesystemCommand_GetProperty
};

inline const FilesystemCommand (&EnumValuesFilesystemCommand())[14] {
  static const FilesystemCommand values[] = {
    FilesystemCommand_Mount,
    FilesystemCommand_Unmount,
    FilesystemCommand_Read,
    FilesystemCommand_Write,
    FilesystemCommand_List,
    FilesystemCommand_Remove,
    FilesystemCommand_Mkdir,
    FilesystemCommand_Rename,
    FilesystemCommand_Copy,
    FilesystemCommand_Move,
    FilesystemCommand_State,
    FilesystemCommand_Absolute,
    FilesystemCommand_SetProperty,
    FilesystemCommand_GetProperty
  };
  return values;
}

inline const char * const *EnumNamesFilesystemCommand() {
  static const char * const names[15] = {
    "Mount",
    "Unmount",
    "Read",
    "Write",
    "List",
    "Remove",
    "Mkdir",
    "Rename",
    "Copy",
    "Move",
    "State",
    "Absolute",
    "SetProperty",
    "GetProperty",
    nullptr
  };
  return names;
}

inline const char *EnumNameFilesystemCommand(FilesystemCommand e) {
  if (::flatbuffers::IsOutRange(e, FilesystemCommand_Mount, FilesystemCommand_GetProperty)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(FilesystemCommand_Mount);
  return EnumNamesFilesystemCommand()[index];
}

enum FileType : int8_t {
  FileType_File = 0,
  FileType_Directory = 1,
  FileType_Symlink = 2,
  FileType_Other = 3,
  FileType_MIN = FileType_File,
  FileType_MAX = FileType_Other
};

inline const FileType (&EnumValuesFileType())[4] {
  static const FileType values[] = {
    FileType_File,
    FileType_Directory,
    FileType_Symlink,
    FileType_Other
  };
  return values;
}

inline const char * const *EnumNamesFileType() {
  static const char * const names[5] = {
    "File",
    "Directory",
    "Symlink",
    "Other",
    nullptr
  };
  return names;
}

inline const char *EnumNameFileType(FileType e) {
  if (::flatbuffers::IsOutRange(e, FileType_File, FileType_Other)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesFileType()[index];
}

struct StringListT : public ::flatbuffers::NativeTable {
  typedef StringList TableType;
  std::vector<std::string> items{};
};

struct StringList FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StringListT NativeTableType;
  typedef StringListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ITEMS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *items() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_ITEMS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ITEMS) &&
           verifier.VerifyVector(items()) &&
           verifier.VerifyVectorOfStrings(items()) &&
           verifier.EndTable();
  }
  StringListT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(StringListT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<StringList> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const StringListT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct StringListBuilder {
  typedef StringList Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_items(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> items) {
    fbb_.AddOffset(StringList::VT_ITEMS, items);
  }
  explicit StringListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StringList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StringList>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StringList> CreateStringList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> items = 0) {
  StringListBuilder builder_(_fbb);
  builder_.add_items(items);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StringList> CreateStringListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *items = nullptr) {
  auto items__ = items ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*items) : 0;
  return sandbox::schemas::filesystem::CreateStringList(
      _fbb,
      items__);
}

::flatbuffers::Offset<StringList> CreateStringList(::flatbuffers::FlatBufferBuilder &_fbb, const StringListT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct FileMetadataT : public ::flatbuffers::NativeTable {
  typedef FileMetadata TableType;
  std::string virtual_path{};
  uint64_t size = 0;
  sandbox::schemas::filesystem::FileType type = sandbox::schemas::filesystem::FileType_File;
  uint64_t creation_time = 0;
  uint64_t modification_time = 0;
  uint64_t access_time = 0;
  bool read_only = false;
};

struct FileMetadata FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FileMetadataT NativeTableType;
  typedef FileMetadataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VIRTUAL_PATH = 4,
    VT_SIZE = 6,
    VT_TYPE = 8,
    VT_CREATION_TIME = 10,
    VT_MODIFICATION_TIME = 12,
    VT_ACCESS_TIME = 14,
    VT_READ_ONLY = 16
  };
  const ::flatbuffers::String *virtual_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VIRTUAL_PATH);
  }
  uint64_t size() const {
    return GetField<uint64_t>(VT_SIZE, 0);
  }
  sandbox::schemas::filesystem::FileType type() const {
    return static_cast<sandbox::schemas::filesystem::FileType>(GetField<int8_t>(VT_TYPE, 0));
  }
  uint64_t creation_time() const {
    return GetField<uint64_t>(VT_CREATION_TIME, 0);
  }
  uint64_t modification_time() const {
    return GetField<uint64_t>(VT_MODIFICATION_TIME, 0);
  }
  uint64_t access_time() const {
    return GetField<uint64_t>(VT_ACCESS_TIME, 0);
  }
  bool read_only() const {
    return GetField<uint8_t>(VT_READ_ONLY, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VIRTUAL_PATH) &&
           verifier.VerifyString(virtual_path()) &&
           VerifyField<uint64_t>(verifier, VT_SIZE, 8) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<uint64_t>(verifier, VT_CREATION_TIME, 8) &&
           VerifyField<uint64_t>(verifier, VT_MODIFICATION_TIME, 8) &&
           VerifyField<uint64_t>(verifier, VT_ACCESS_TIME, 8) &&
           VerifyField<uint8_t>(verifier, VT_READ_ONLY, 1) &&
           verifier.EndTable();
  }
  FileMetadataT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(FileMetadataT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<FileMetadata> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const FileMetadataT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct FileMetadataBuilder {
  typedef FileMetadata Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_virtual_path(::flatbuffers::Offset<::flatbuffers::String> virtual_path) {
    fbb_.AddOffset(FileMetadata::VT_VIRTUAL_PATH, virtual_path);
  }
  void add_size(uint64_t size) {
    fbb_.AddElement<uint64_t>(FileMetadata::VT_SIZE, size, 0);
  }
  void add_type(sandbox::schemas::filesystem::FileType type) {
    fbb_.AddElement<int8_t>(FileMetadata::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_creation_time(uint64_t creation_time) {
    fbb_.AddElement<uint64_t>(FileMetadata::VT_CREATION_TIME, creation_time, 0);
  }
  void add_modification_time(uint64_t modification_time) {
    fbb_.AddElement<uint64_t>(FileMetadata::VT_MODIFICATION_TIME, modification_time, 0);
  }
  void add_access_time(uint64_t access_time) {
    fbb_.AddElement<uint64_t>(FileMetadata::VT_ACCESS_TIME, access_time, 0);
  }
  void add_read_only(bool read_only) {
    fbb_.AddElement<uint8_t>(FileMetadata::VT_READ_ONLY, static_cast<uint8_t>(read_only), 0);
  }
  explicit FileMetadataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FileMetadata> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FileMetadata>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FileMetadata> CreateFileMetadata(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> virtual_path = 0,
    uint64_t size = 0,
    sandbox::schemas::filesystem::FileType type = sandbox::schemas::filesystem::FileType_File,
    uint64_t creation_time = 0,
    uint64_t modification_time = 0,
    uint64_t access_time = 0,
    bool read_only = false) {
  FileMetadataBuilder builder_(_fbb);
  builder_.add_access_time(access_time);
  builder_.add_modification_time(modification_time);
  builder_.add_creation_time(creation_time);
  builder_.add_size(size);
  builder_.add_virtual_path(virtual_path);
  builder_.add_read_only(read_only);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FileMetadata> CreateFileMetadataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *virtual_path = nullptr,
    uint64_t size = 0,
    sandbox::schemas::filesystem::FileType type = sandbox::schemas::filesystem::FileType_File,
    uint64_t creation_time = 0,
    uint64_t modification_time = 0,
    uint64_t access_time = 0,
    bool read_only = false) {
  auto virtual_path__ = virtual_path ? _fbb.CreateString(virtual_path) : 0;
  return sandbox::schemas::filesystem::CreateFileMetadata(
      _fbb,
      virtual_path__,
      size,
      type,
      creation_time,
      modification_time,
      access_time,
      read_only);
}

::flatbuffers::Offset<FileMetadata> CreateFileMetadata(::flatbuffers::FlatBufferBuilder &_fbb, const FileMetadataT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct MountArgsT : public ::flatbuffers::NativeTable {
  typedef MountArgs TableType;
  std::string physical_path{};
  std::string virtual_prefix{};
  bool read_only = false;
  uint64_t out_result_ptr = 0;
};

struct MountArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MountArgsT NativeTableType;
  typedef MountArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PHYSICAL_PATH = 4,
    VT_VIRTUAL_PREFIX = 6,
    VT_READ_ONLY = 8,
    VT_OUT_RESULT_PTR = 10
  };
  const ::flatbuffers::String *physical_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PHYSICAL_PATH);
  }
  const ::flatbuffers::String *virtual_prefix() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VIRTUAL_PREFIX);
  }
  bool read_only() const {
    return GetField<uint8_t>(VT_READ_ONLY, 0) != 0;
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PHYSICAL_PATH) &&
           verifier.VerifyString(physical_path()) &&
           VerifyOffset(verifier, VT_VIRTUAL_PREFIX) &&
           verifier.VerifyString(virtual_prefix()) &&
           VerifyField<uint8_t>(verifier, VT_READ_ONLY, 1) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  MountArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MountArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<MountArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MountArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MountArgsBuilder {
  typedef MountArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_physical_path(::flatbuffers::Offset<::flatbuffers::String> physical_path) {
    fbb_.AddOffset(MountArgs::VT_PHYSICAL_PATH, physical_path);
  }
  void add_virtual_prefix(::flatbuffers::Offset<::flatbuffers::String> virtual_prefix) {
    fbb_.AddOffset(MountArgs::VT_VIRTUAL_PREFIX, virtual_prefix);
  }
  void add_read_only(bool read_only) {
    fbb_.AddElement<uint8_t>(MountArgs::VT_READ_ONLY, static_cast<uint8_t>(read_only), 0);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(MountArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit MountArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MountArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MountArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MountArgs> CreateMountArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> physical_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> virtual_prefix = 0,
    bool read_only = false,
    uint64_t out_result_ptr = 0) {
  MountArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_virtual_prefix(virtual_prefix);
  builder_.add_physical_path(physical_path);
  builder_.add_read_only(read_only);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MountArgs> CreateMountArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *physical_path = nullptr,
    const char *virtual_prefix = nullptr,
    bool read_only = false,
    uint64_t out_result_ptr = 0) {
  auto physical_path__ = physical_path ? _fbb.CreateString(physical_path) : 0;
  auto virtual_prefix__ = virtual_prefix ? _fbb.CreateString(virtual_prefix) : 0;
  return sandbox::schemas::filesystem::CreateMountArgs(
      _fbb,
      physical_path__,
      virtual_prefix__,
      read_only,
      out_result_ptr);
}

::flatbuffers::Offset<MountArgs> CreateMountArgs(::flatbuffers::FlatBufferBuilder &_fbb, const MountArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct UnmountArgsT : public ::flatbuffers::NativeTable {
  typedef UnmountArgs TableType;
  std::string virtual_prefix{};
  uint64_t out_result_ptr = 0;
};

struct UnmountArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UnmountArgsT NativeTableType;
  typedef UnmountArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VIRTUAL_PREFIX = 4,
    VT_OUT_RESULT_PTR = 6
  };
  const ::flatbuffers::String *virtual_prefix() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VIRTUAL_PREFIX);
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VIRTUAL_PREFIX) &&
           verifier.VerifyString(virtual_prefix()) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  UnmountArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(UnmountArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<UnmountArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const UnmountArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct UnmountArgsBuilder {
  typedef UnmountArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_virtual_prefix(::flatbuffers::Offset<::flatbuffers::String> virtual_prefix) {
    fbb_.AddOffset(UnmountArgs::VT_VIRTUAL_PREFIX, virtual_prefix);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(UnmountArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit UnmountArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UnmountArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UnmountArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UnmountArgs> CreateUnmountArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> virtual_prefix = 0,
    uint64_t out_result_ptr = 0) {
  UnmountArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_virtual_prefix(virtual_prefix);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UnmountArgs> CreateUnmountArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *virtual_prefix = nullptr,
    uint64_t out_result_ptr = 0) {
  auto virtual_prefix__ = virtual_prefix ? _fbb.CreateString(virtual_prefix) : 0;
  return sandbox::schemas::filesystem::CreateUnmountArgs(
      _fbb,
      virtual_prefix__,
      out_result_ptr);
}

::flatbuffers::Offset<UnmountArgs> CreateUnmountArgs(::flatbuffers::FlatBufferBuilder &_fbb, const UnmountArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ReadArgsT : public ::flatbuffers::NativeTable {
  typedef ReadArgs TableType;
  std::string virtual_path{};
  uint64_t out_payload_ptr = 0;
  uint64_t out_result_ptr = 0;
};

struct ReadArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ReadArgsT NativeTableType;
  typedef ReadArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VIRTUAL_PATH = 4,
    VT_OUT_PAYLOAD_PTR = 6,
    VT_OUT_RESULT_PTR = 8
  };
  const ::flatbuffers::String *virtual_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VIRTUAL_PATH);
  }
  uint64_t out_payload_ptr() const {
    return GetField<uint64_t>(VT_OUT_PAYLOAD_PTR, 0);
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VIRTUAL_PATH) &&
           verifier.VerifyString(virtual_path()) &&
           VerifyField<uint64_t>(verifier, VT_OUT_PAYLOAD_PTR, 8) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  ReadArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ReadArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ReadArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ReadArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ReadArgsBuilder {
  typedef ReadArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_virtual_path(::flatbuffers::Offset<::flatbuffers::String> virtual_path) {
    fbb_.AddOffset(ReadArgs::VT_VIRTUAL_PATH, virtual_path);
  }
  void add_out_payload_ptr(uint64_t out_payload_ptr) {
    fbb_.AddElement<uint64_t>(ReadArgs::VT_OUT_PAYLOAD_PTR, out_payload_ptr, 0);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(ReadArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit ReadArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ReadArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ReadArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ReadArgs> CreateReadArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> virtual_path = 0,
    uint64_t out_payload_ptr = 0,
    uint64_t out_result_ptr = 0) {
  ReadArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_out_payload_ptr(out_payload_ptr);
  builder_.add_virtual_path(virtual_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ReadArgs> CreateReadArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *virtual_path = nullptr,
    uint64_t out_payload_ptr = 0,
    uint64_t out_result_ptr = 0) {
  auto virtual_path__ = virtual_path ? _fbb.CreateString(virtual_path) : 0;
  return sandbox::schemas::filesystem::CreateReadArgs(
      _fbb,
      virtual_path__,
      out_payload_ptr,
      out_result_ptr);
}

::flatbuffers::Offset<ReadArgs> CreateReadArgs(::flatbuffers::FlatBufferBuilder &_fbb, const ReadArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct WriteArgsT : public ::flatbuffers::NativeTable {
  typedef WriteArgs TableType;
  std::string virtual_path{};
  std::vector<uint8_t> data{};
  bool append = false;
  uint64_t out_result_ptr = 0;
};

struct WriteArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WriteArgsT NativeTableType;
  typedef WriteArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VIRTUAL_PATH = 4,
    VT_DATA = 6,
    VT_APPEND = 8,
    VT_OUT_RESULT_PTR = 10
  };
  const ::flatbuffers::String *virtual_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VIRTUAL_PATH);
  }
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool append() const {
    return GetField<uint8_t>(VT_APPEND, 0) != 0;
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VIRTUAL_PATH) &&
           verifier.VerifyString(virtual_path()) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           VerifyField<uint8_t>(verifier, VT_APPEND, 1) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  WriteArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(WriteArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<WriteArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const WriteArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct WriteArgsBuilder {
  typedef WriteArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_virtual_path(::flatbuffers::Offset<::flatbuffers::String> virtual_path) {
    fbb_.AddOffset(WriteArgs::VT_VIRTUAL_PATH, virtual_path);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(WriteArgs::VT_DATA, data);
  }
  void add_append(bool append) {
    fbb_.AddElement<uint8_t>(WriteArgs::VT_APPEND, static_cast<uint8_t>(append), 0);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(WriteArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit WriteArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WriteArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WriteArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WriteArgs> CreateWriteArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> virtual_path = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0,
    bool append = false,
    uint64_t out_result_ptr = 0) {
  WriteArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_data(data);
  builder_.add_virtual_path(virtual_path);
  builder_.add_append(append);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<WriteArgs> CreateWriteArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *virtual_path = nullptr,
    const std::vector<uint8_t> *data = nullptr,
    bool append = false,
    uint64_t out_result_ptr = 0) {
  auto virtual_path__ = virtual_path ? _fbb.CreateString(virtual_path) : 0;
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return sandbox::schemas::filesystem::CreateWriteArgs(
      _fbb,
      virtual_path__,
      data__,
      append,
      out_result_ptr);
}

::flatbuffers::Offset<WriteArgs> CreateWriteArgs(::flatbuffers::FlatBufferBuilder &_fbb, const WriteArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ListArgsT : public ::flatbuffers::NativeTable {
  typedef ListArgs TableType;
  std::string virtual_path{};
  bool recursive = false;
  uint64_t out_payload_ptr = 0;
  uint64_t out_result_ptr = 0;
};

struct ListArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ListArgsT NativeTableType;
  typedef ListArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VIRTUAL_PATH = 4,
    VT_RECURSIVE = 6,
    VT_OUT_PAYLOAD_PTR = 8,
    VT_OUT_RESULT_PTR = 10
  };
  const ::flatbuffers::String *virtual_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VIRTUAL_PATH);
  }
  bool recursive() const {
    return GetField<uint8_t>(VT_RECURSIVE, 0) != 0;
  }
  uint64_t out_payload_ptr() const {
    return GetField<uint64_t>(VT_OUT_PAYLOAD_PTR, 0);
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VIRTUAL_PATH) &&
           verifier.VerifyString(virtual_path()) &&
           VerifyField<uint8_t>(verifier, VT_RECURSIVE, 1) &&
           VerifyField<uint64_t>(verifier, VT_OUT_PAYLOAD_PTR, 8) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  ListArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ListArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ListArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ListArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ListArgsBuilder {
  typedef ListArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_virtual_path(::flatbuffers::Offset<::flatbuffers::String> virtual_path) {
    fbb_.AddOffset(ListArgs::VT_VIRTUAL_PATH, virtual_path);
  }
  void add_recursive(bool recursive) {
    fbb_.AddElement<uint8_t>(ListArgs::VT_RECURSIVE, static_cast<uint8_t>(recursive), 0);
  }
  void add_out_payload_ptr(uint64_t out_payload_ptr) {
    fbb_.AddElement<uint64_t>(ListArgs::VT_OUT_PAYLOAD_PTR, out_payload_ptr, 0);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(ListArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit ListArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ListArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ListArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ListArgs> CreateListArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> virtual_path = 0,
    bool recursive = false,
    uint64_t out_payload_ptr = 0,
    uint64_t out_result_ptr = 0) {
  ListArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_out_payload_ptr(out_payload_ptr);
  builder_.add_virtual_path(virtual_path);
  builder_.add_recursive(recursive);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ListArgs> CreateListArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *virtual_path = nullptr,
    bool recursive = false,
    uint64_t out_payload_ptr = 0,
    uint64_t out_result_ptr = 0) {
  auto virtual_path__ = virtual_path ? _fbb.CreateString(virtual_path) : 0;
  return sandbox::schemas::filesystem::CreateListArgs(
      _fbb,
      virtual_path__,
      recursive,
      out_payload_ptr,
      out_result_ptr);
}

::flatbuffers::Offset<ListArgs> CreateListArgs(::flatbuffers::FlatBufferBuilder &_fbb, const ListArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct RemoveArgsT : public ::flatbuffers::NativeTable {
  typedef RemoveArgs TableType;
  std::string virtual_path{};
  uint64_t out_result_ptr = 0;
};

struct RemoveArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RemoveArgsT NativeTableType;
  typedef RemoveArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VIRTUAL_PATH = 4,
    VT_OUT_RESULT_PTR = 6
  };
  const ::flatbuffers::String *virtual_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VIRTUAL_PATH);
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VIRTUAL_PATH) &&
           verifier.VerifyString(virtual_path()) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  RemoveArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RemoveArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<RemoveArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RemoveArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct RemoveArgsBuilder {
  typedef RemoveArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_virtual_path(::flatbuffers::Offset<::flatbuffers::String> virtual_path) {
    fbb_.AddOffset(RemoveArgs::VT_VIRTUAL_PATH, virtual_path);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(RemoveArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit RemoveArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RemoveArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RemoveArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RemoveArgs> CreateRemoveArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> virtual_path = 0,
    uint64_t out_result_ptr = 0) {
  RemoveArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_virtual_path(virtual_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RemoveArgs> CreateRemoveArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *virtual_path = nullptr,
    uint64_t out_result_ptr = 0) {
  auto virtual_path__ = virtual_path ? _fbb.CreateString(virtual_path) : 0;
  return sandbox::schemas::filesystem::CreateRemoveArgs(
      _fbb,
      virtual_path__,
      out_result_ptr);
}

::flatbuffers::Offset<RemoveArgs> CreateRemoveArgs(::flatbuffers::FlatBufferBuilder &_fbb, const RemoveArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct MkdirArgsT : public ::flatbuffers::NativeTable {
  typedef MkdirArgs TableType;
  std::string virtual_path{};
  uint64_t out_result_ptr = 0;
};

struct MkdirArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MkdirArgsT NativeTableType;
  typedef MkdirArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VIRTUAL_PATH = 4,
    VT_OUT_RESULT_PTR = 6
  };
  const ::flatbuffers::String *virtual_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VIRTUAL_PATH);
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VIRTUAL_PATH) &&
           verifier.VerifyString(virtual_path()) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  MkdirArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MkdirArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<MkdirArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MkdirArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MkdirArgsBuilder {
  typedef MkdirArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_virtual_path(::flatbuffers::Offset<::flatbuffers::String> virtual_path) {
    fbb_.AddOffset(MkdirArgs::VT_VIRTUAL_PATH, virtual_path);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(MkdirArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit MkdirArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MkdirArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MkdirArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MkdirArgs> CreateMkdirArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> virtual_path = 0,
    uint64_t out_result_ptr = 0) {
  MkdirArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_virtual_path(virtual_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MkdirArgs> CreateMkdirArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *virtual_path = nullptr,
    uint64_t out_result_ptr = 0) {
  auto virtual_path__ = virtual_path ? _fbb.CreateString(virtual_path) : 0;
  return sandbox::schemas::filesystem::CreateMkdirArgs(
      _fbb,
      virtual_path__,
      out_result_ptr);
}

::flatbuffers::Offset<MkdirArgs> CreateMkdirArgs(::flatbuffers::FlatBufferBuilder &_fbb, const MkdirArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct RenameArgsT : public ::flatbuffers::NativeTable {
  typedef RenameArgs TableType;
  std::string old_virtual_path{};
  std::string new_virtual_path{};
  uint64_t out_result_ptr = 0;
};

struct RenameArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RenameArgsT NativeTableType;
  typedef RenameArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OLD_VIRTUAL_PATH = 4,
    VT_NEW_VIRTUAL_PATH = 6,
    VT_OUT_RESULT_PTR = 8
  };
  const ::flatbuffers::String *old_virtual_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OLD_VIRTUAL_PATH);
  }
  const ::flatbuffers::String *new_virtual_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NEW_VIRTUAL_PATH);
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_OLD_VIRTUAL_PATH) &&
           verifier.VerifyString(old_virtual_path()) &&
           VerifyOffset(verifier, VT_NEW_VIRTUAL_PATH) &&
           verifier.VerifyString(new_virtual_path()) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  RenameArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RenameArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<RenameArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RenameArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct RenameArgsBuilder {
  typedef RenameArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_old_virtual_path(::flatbuffers::Offset<::flatbuffers::String> old_virtual_path) {
    fbb_.AddOffset(RenameArgs::VT_OLD_VIRTUAL_PATH, old_virtual_path);
  }
  void add_new_virtual_path(::flatbuffers::Offset<::flatbuffers::String> new_virtual_path) {
    fbb_.AddOffset(RenameArgs::VT_NEW_VIRTUAL_PATH, new_virtual_path);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(RenameArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit RenameArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RenameArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RenameArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RenameArgs> CreateRenameArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> old_virtual_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> new_virtual_path = 0,
    uint64_t out_result_ptr = 0) {
  RenameArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_new_virtual_path(new_virtual_path);
  builder_.add_old_virtual_path(old_virtual_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RenameArgs> CreateRenameArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *old_virtual_path = nullptr,
    const char *new_virtual_path = nullptr,
    uint64_t out_result_ptr = 0) {
  auto old_virtual_path__ = old_virtual_path ? _fbb.CreateString(old_virtual_path) : 0;
  auto new_virtual_path__ = new_virtual_path ? _fbb.CreateString(new_virtual_path) : 0;
  return sandbox::schemas::filesystem::CreateRenameArgs(
      _fbb,
      old_virtual_path__,
      new_virtual_path__,
      out_result_ptr);
}

::flatbuffers::Offset<RenameArgs> CreateRenameArgs(::flatbuffers::FlatBufferBuilder &_fbb, const RenameArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CopyArgsT : public ::flatbuffers::NativeTable {
  typedef CopyArgs TableType;
  std::string source_virtual_path{};
  std::string destination_virtual_path{};
  uint64_t out_result_ptr = 0;
};

struct CopyArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CopyArgsT NativeTableType;
  typedef CopyArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SOURCE_VIRTUAL_PATH = 4,
    VT_DESTINATION_VIRTUAL_PATH = 6,
    VT_OUT_RESULT_PTR = 8
  };
  const ::flatbuffers::String *source_virtual_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_VIRTUAL_PATH);
  }
  const ::flatbuffers::String *destination_virtual_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESTINATION_VIRTUAL_PATH);
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SOURCE_VIRTUAL_PATH) &&
           verifier.VerifyString(source_virtual_path()) &&
           VerifyOffset(verifier, VT_DESTINATION_VIRTUAL_PATH) &&
           verifier.VerifyString(destination_virtual_path()) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  CopyArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CopyArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CopyArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CopyArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CopyArgsBuilder {
  typedef CopyArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_source_virtual_path(::flatbuffers::Offset<::flatbuffers::String> source_virtual_path) {
    fbb_.AddOffset(CopyArgs::VT_SOURCE_VIRTUAL_PATH, source_virtual_path);
  }
  void add_destination_virtual_path(::flatbuffers::Offset<::flatbuffers::String> destination_virtual_path) {
    fbb_.AddOffset(CopyArgs::VT_DESTINATION_VIRTUAL_PATH, destination_virtual_path);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(CopyArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit CopyArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CopyArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CopyArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CopyArgs> CreateCopyArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> source_virtual_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> destination_virtual_path = 0,
    uint64_t out_result_ptr = 0) {
  CopyArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_destination_virtual_path(destination_virtual_path);
  builder_.add_source_virtual_path(source_virtual_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CopyArgs> CreateCopyArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *source_virtual_path = nullptr,
    const char *destination_virtual_path = nullptr,
    uint64_t out_result_ptr = 0) {
  auto source_virtual_path__ = source_virtual_path ? _fbb.CreateString(source_virtual_path) : 0;
  auto destination_virtual_path__ = destination_virtual_path ? _fbb.CreateString(destination_virtual_path) : 0;
  return sandbox::schemas::filesystem::CreateCopyArgs(
      _fbb,
      source_virtual_path__,
      destination_virtual_path__,
      out_result_ptr);
}

::flatbuffers::Offset<CopyArgs> CreateCopyArgs(::flatbuffers::FlatBufferBuilder &_fbb, const CopyArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct MoveArgsT : public ::flatbuffers::NativeTable {
  typedef MoveArgs TableType;
  std::string source_virtual_path{};
  std::string destination_virtual_path{};
  uint64_t out_result_ptr = 0;
};

struct MoveArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MoveArgsT NativeTableType;
  typedef MoveArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SOURCE_VIRTUAL_PATH = 4,
    VT_DESTINATION_VIRTUAL_PATH = 6,
    VT_OUT_RESULT_PTR = 8
  };
  const ::flatbuffers::String *source_virtual_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_VIRTUAL_PATH);
  }
  const ::flatbuffers::String *destination_virtual_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESTINATION_VIRTUAL_PATH);
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SOURCE_VIRTUAL_PATH) &&
           verifier.VerifyString(source_virtual_path()) &&
           VerifyOffset(verifier, VT_DESTINATION_VIRTUAL_PATH) &&
           verifier.VerifyString(destination_virtual_path()) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  MoveArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MoveArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<MoveArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MoveArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MoveArgsBuilder {
  typedef MoveArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_source_virtual_path(::flatbuffers::Offset<::flatbuffers::String> source_virtual_path) {
    fbb_.AddOffset(MoveArgs::VT_SOURCE_VIRTUAL_PATH, source_virtual_path);
  }
  void add_destination_virtual_path(::flatbuffers::Offset<::flatbuffers::String> destination_virtual_path) {
    fbb_.AddOffset(MoveArgs::VT_DESTINATION_VIRTUAL_PATH, destination_virtual_path);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(MoveArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit MoveArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MoveArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MoveArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MoveArgs> CreateMoveArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> source_virtual_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> destination_virtual_path = 0,
    uint64_t out_result_ptr = 0) {
  MoveArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_destination_virtual_path(destination_virtual_path);
  builder_.add_source_virtual_path(source_virtual_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MoveArgs> CreateMoveArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *source_virtual_path = nullptr,
    const char *destination_virtual_path = nullptr,
    uint64_t out_result_ptr = 0) {
  auto source_virtual_path__ = source_virtual_path ? _fbb.CreateString(source_virtual_path) : 0;
  auto destination_virtual_path__ = destination_virtual_path ? _fbb.CreateString(destination_virtual_path) : 0;
  return sandbox::schemas::filesystem::CreateMoveArgs(
      _fbb,
      source_virtual_path__,
      destination_virtual_path__,
      out_result_ptr);
}

::flatbuffers::Offset<MoveArgs> CreateMoveArgs(::flatbuffers::FlatBufferBuilder &_fbb, const MoveArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct StateArgsT : public ::flatbuffers::NativeTable {
  typedef StateArgs TableType;
  std::string virtual_path{};
  uint64_t out_payload_ptr = 0;
  uint64_t out_result_ptr = 0;
};

struct StateArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StateArgsT NativeTableType;
  typedef StateArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VIRTUAL_PATH = 4,
    VT_OUT_PAYLOAD_PTR = 6,
    VT_OUT_RESULT_PTR = 8
  };
  const ::flatbuffers::String *virtual_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VIRTUAL_PATH);
  }
  uint64_t out_payload_ptr() const {
    return GetField<uint64_t>(VT_OUT_PAYLOAD_PTR, 0);
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VIRTUAL_PATH) &&
           verifier.VerifyString(virtual_path()) &&
           VerifyField<uint64_t>(verifier, VT_OUT_PAYLOAD_PTR, 8) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  StateArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(StateArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<StateArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const StateArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct StateArgsBuilder {
  typedef StateArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_virtual_path(::flatbuffers::Offset<::flatbuffers::String> virtual_path) {
    fbb_.AddOffset(StateArgs::VT_VIRTUAL_PATH, virtual_path);
  }
  void add_out_payload_ptr(uint64_t out_payload_ptr) {
    fbb_.AddElement<uint64_t>(StateArgs::VT_OUT_PAYLOAD_PTR, out_payload_ptr, 0);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(StateArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit StateArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StateArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StateArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StateArgs> CreateStateArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> virtual_path = 0,
    uint64_t out_payload_ptr = 0,
    uint64_t out_result_ptr = 0) {
  StateArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_out_payload_ptr(out_payload_ptr);
  builder_.add_virtual_path(virtual_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StateArgs> CreateStateArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *virtual_path = nullptr,
    uint64_t out_payload_ptr = 0,
    uint64_t out_result_ptr = 0) {
  auto virtual_path__ = virtual_path ? _fbb.CreateString(virtual_path) : 0;
  return sandbox::schemas::filesystem::CreateStateArgs(
      _fbb,
      virtual_path__,
      out_payload_ptr,
      out_result_ptr);
}

::flatbuffers::Offset<StateArgs> CreateStateArgs(::flatbuffers::FlatBufferBuilder &_fbb, const StateArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct AbsoluteArgsT : public ::flatbuffers::NativeTable {
  typedef AbsoluteArgs TableType;
  std::string virtual_path{};
  uint64_t out_payload_ptr = 0;
  uint64_t out_result_ptr = 0;
};

struct AbsoluteArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AbsoluteArgsT NativeTableType;
  typedef AbsoluteArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VIRTUAL_PATH = 4,
    VT_OUT_PAYLOAD_PTR = 6,
    VT_OUT_RESULT_PTR = 8
  };
  const ::flatbuffers::String *virtual_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VIRTUAL_PATH);
  }
  uint64_t out_payload_ptr() const {
    return GetField<uint64_t>(VT_OUT_PAYLOAD_PTR, 0);
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VIRTUAL_PATH) &&
           verifier.VerifyString(virtual_path()) &&
           VerifyField<uint64_t>(verifier, VT_OUT_PAYLOAD_PTR, 8) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  AbsoluteArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AbsoluteArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<AbsoluteArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AbsoluteArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AbsoluteArgsBuilder {
  typedef AbsoluteArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_virtual_path(::flatbuffers::Offset<::flatbuffers::String> virtual_path) {
    fbb_.AddOffset(AbsoluteArgs::VT_VIRTUAL_PATH, virtual_path);
  }
  void add_out_payload_ptr(uint64_t out_payload_ptr) {
    fbb_.AddElement<uint64_t>(AbsoluteArgs::VT_OUT_PAYLOAD_PTR, out_payload_ptr, 0);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(AbsoluteArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit AbsoluteArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AbsoluteArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AbsoluteArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AbsoluteArgs> CreateAbsoluteArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> virtual_path = 0,
    uint64_t out_payload_ptr = 0,
    uint64_t out_result_ptr = 0) {
  AbsoluteArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_out_payload_ptr(out_payload_ptr);
  builder_.add_virtual_path(virtual_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AbsoluteArgs> CreateAbsoluteArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *virtual_path = nullptr,
    uint64_t out_payload_ptr = 0,
    uint64_t out_result_ptr = 0) {
  auto virtual_path__ = virtual_path ? _fbb.CreateString(virtual_path) : 0;
  return sandbox::schemas::filesystem::CreateAbsoluteArgs(
      _fbb,
      virtual_path__,
      out_payload_ptr,
      out_result_ptr);
}

::flatbuffers::Offset<AbsoluteArgs> CreateAbsoluteArgs(::flatbuffers::FlatBufferBuilder &_fbb, const AbsoluteArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SetPropertyArgsT : public ::flatbuffers::NativeTable {
  typedef SetPropertyArgs TableType;
  std::string key{};
  std::string json_value{};
};

struct SetPropertyArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetPropertyArgsT NativeTableType;
  typedef SetPropertyArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_JSON_VALUE = 6
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  const ::flatbuffers::String *json_value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_JSON_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyOffset(verifier, VT_JSON_VALUE) &&
           verifier.VerifyString(json_value()) &&
           verifier.EndTable();
  }
  SetPropertyArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SetPropertyArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SetPropertyArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetPropertyArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SetPropertyArgsBuilder {
  typedef SetPropertyArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(SetPropertyArgs::VT_KEY, key);
  }
  void add_json_value(::flatbuffers::Offset<::flatbuffers::String> json_value) {
    fbb_.AddOffset(SetPropertyArgs::VT_JSON_VALUE, json_value);
  }
  explicit SetPropertyArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetPropertyArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetPropertyArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetPropertyArgs> CreateSetPropertyArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    ::flatbuffers::Offset<::flatbuffers::String> json_value = 0) {
  SetPropertyArgsBuilder builder_(_fbb);
  builder_.add_json_value(json_value);
  builder_.add_key(key);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetPropertyArgs> CreateSetPropertyArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    const char *json_value = nullptr) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  auto json_value__ = json_value ? _fbb.CreateString(json_value) : 0;
  return sandbox::schemas::filesystem::CreateSetPropertyArgs(
      _fbb,
      key__,
      json_value__);
}

::flatbuffers::Offset<SetPropertyArgs> CreateSetPropertyArgs(::flatbuffers::FlatBufferBuilder &_fbb, const SetPropertyArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct GetPropertyArgsT : public ::flatbuffers::NativeTable {
  typedef GetPropertyArgs TableType;
  std::string key{};
  uint64_t out_payload_ptr = 0;
  uint64_t out_result_ptr = 0;
};

struct GetPropertyArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GetPropertyArgsT NativeTableType;
  typedef GetPropertyArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_OUT_PAYLOAD_PTR = 6,
    VT_OUT_RESULT_PTR = 8
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  uint64_t out_payload_ptr() const {
    return GetField<uint64_t>(VT_OUT_PAYLOAD_PTR, 0);
  }
  uint64_t out_result_ptr() const {
    return GetField<uint64_t>(VT_OUT_RESULT_PTR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyField<uint64_t>(verifier, VT_OUT_PAYLOAD_PTR, 8) &&
           VerifyField<uint64_t>(verifier, VT_OUT_RESULT_PTR, 8) &&
           verifier.EndTable();
  }
  GetPropertyArgsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(GetPropertyArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<GetPropertyArgs> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GetPropertyArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct GetPropertyArgsBuilder {
  typedef GetPropertyArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(GetPropertyArgs::VT_KEY, key);
  }
  void add_out_payload_ptr(uint64_t out_payload_ptr) {
    fbb_.AddElement<uint64_t>(GetPropertyArgs::VT_OUT_PAYLOAD_PTR, out_payload_ptr, 0);
  }
  void add_out_result_ptr(uint64_t out_result_ptr) {
    fbb_.AddElement<uint64_t>(GetPropertyArgs::VT_OUT_RESULT_PTR, out_result_ptr, 0);
  }
  explicit GetPropertyArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GetPropertyArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GetPropertyArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GetPropertyArgs> CreateGetPropertyArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    uint64_t out_payload_ptr = 0,
    uint64_t out_result_ptr = 0) {
  GetPropertyArgsBuilder builder_(_fbb);
  builder_.add_out_result_ptr(out_result_ptr);
  builder_.add_out_payload_ptr(out_payload_ptr);
  builder_.add_key(key);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GetPropertyArgs> CreateGetPropertyArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    uint64_t out_payload_ptr = 0,
    uint64_t out_result_ptr = 0) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  return sandbox::schemas::filesystem::CreateGetPropertyArgs(
      _fbb,
      key__,
      out_payload_ptr,
      out_result_ptr);
}

::flatbuffers::Offset<GetPropertyArgs> CreateGetPropertyArgs(::flatbuffers::FlatBufferBuilder &_fbb, const GetPropertyArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline StringListT *StringList::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<StringListT>(new StringListT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void StringList::UnPackTo(StringListT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = items(); if (_e) { _o->items.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->items[_i] = _e->Get(_i)->str(); } } else { _o->items.resize(0); } }
}

inline ::flatbuffers::Offset<StringList> StringList::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const StringListT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateStringList(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<StringList> CreateStringList(::flatbuffers::FlatBufferBuilder &_fbb, const StringListT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const StringListT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _items = _o->items.size() ? _fbb.CreateVectorOfStrings(_o->items) : 0;
  return sandbox::schemas::filesystem::CreateStringList(
      _fbb,
      _items);
}

inline FileMetadataT *FileMetadata::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<FileMetadataT>(new FileMetadataT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void FileMetadata::UnPackTo(FileMetadataT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = virtual_path(); if (_e) _o->virtual_path = _e->str(); }
  { auto _e = size(); _o->size = _e; }
  { auto _e = type(); _o->type = _e; }
  { auto _e = creation_time(); _o->creation_time = _e; }
  { auto _e = modification_time(); _o->modification_time = _e; }
  { auto _e = access_time(); _o->access_time = _e; }
  { auto _e = read_only(); _o->read_only = _e; }
}

inline ::flatbuffers::Offset<FileMetadata> FileMetadata::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const FileMetadataT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateFileMetadata(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<FileMetadata> CreateFileMetadata(::flatbuffers::FlatBufferBuilder &_fbb, const FileMetadataT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const FileMetadataT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _virtual_path = _o->virtual_path.empty() ? 0 : _fbb.CreateString(_o->virtual_path);
  auto _size = _o->size;
  auto _type = _o->type;
  auto _creation_time = _o->creation_time;
  auto _modification_time = _o->modification_time;
  auto _access_time = _o->access_time;
  auto _read_only = _o->read_only;
  return sandbox::schemas::filesystem::CreateFileMetadata(
      _fbb,
      _virtual_path,
      _size,
      _type,
      _creation_time,
      _modification_time,
      _access_time,
      _read_only);
}

inline MountArgsT *MountArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<MountArgsT>(new MountArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void MountArgs::UnPackTo(MountArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = physical_path(); if (_e) _o->physical_path = _e->str(); }
  { auto _e = virtual_prefix(); if (_e) _o->virtual_prefix = _e->str(); }
  { auto _e = read_only(); _o->read_only = _e; }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<MountArgs> MountArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MountArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMountArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<MountArgs> CreateMountArgs(::flatbuffers::FlatBufferBuilder &_fbb, const MountArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MountArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _physical_path = _o->physical_path.empty() ? 0 : _fbb.CreateString(_o->physical_path);
  auto _virtual_prefix = _o->virtual_prefix.empty() ? 0 : _fbb.CreateString(_o->virtual_prefix);
  auto _read_only = _o->read_only;
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::filesystem::CreateMountArgs(
      _fbb,
      _physical_path,
      _virtual_prefix,
      _read_only,
      _out_result_ptr);
}

inline UnmountArgsT *UnmountArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<UnmountArgsT>(new UnmountArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void UnmountArgs::UnPackTo(UnmountArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = virtual_prefix(); if (_e) _o->virtual_prefix = _e->str(); }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<UnmountArgs> UnmountArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const UnmountArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateUnmountArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<UnmountArgs> CreateUnmountArgs(::flatbuffers::FlatBufferBuilder &_fbb, const UnmountArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const UnmountArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _virtual_prefix = _o->virtual_prefix.empty() ? 0 : _fbb.CreateString(_o->virtual_prefix);
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::filesystem::CreateUnmountArgs(
      _fbb,
      _virtual_prefix,
      _out_result_ptr);
}

inline ReadArgsT *ReadArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ReadArgsT>(new ReadArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ReadArgs::UnPackTo(ReadArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = virtual_path(); if (_e) _o->virtual_path = _e->str(); }
  { auto _e = out_payload_ptr(); _o->out_payload_ptr = _e; }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<ReadArgs> ReadArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ReadArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateReadArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ReadArgs> CreateReadArgs(::flatbuffers::FlatBufferBuilder &_fbb, const ReadArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ReadArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _virtual_path = _o->virtual_path.empty() ? 0 : _fbb.CreateString(_o->virtual_path);
  auto _out_payload_ptr = _o->out_payload_ptr;
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::filesystem::CreateReadArgs(
      _fbb,
      _virtual_path,
      _out_payload_ptr,
      _out_result_ptr);
}

inline WriteArgsT *WriteArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<WriteArgsT>(new WriteArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void WriteArgs::UnPackTo(WriteArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = virtual_path(); if (_e) _o->virtual_path = _e->str(); }
  { auto _e = data(); if (_e) { _o->data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->data.begin()); } }
  { auto _e = append(); _o->append = _e; }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<WriteArgs> WriteArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const WriteArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateWriteArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<WriteArgs> CreateWriteArgs(::flatbuffers::FlatBufferBuilder &_fbb, const WriteArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const WriteArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _virtual_path = _o->virtual_path.empty() ? 0 : _fbb.CreateString(_o->virtual_path);
  auto _data = _o->data.size() ? _fbb.CreateVector(_o->data) : 0;
  auto _append = _o->append;
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::filesystem::CreateWriteArgs(
      _fbb,
      _virtual_path,
      _data,
      _append,
      _out_result_ptr);
}

inline ListArgsT *ListArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ListArgsT>(new ListArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ListArgs::UnPackTo(ListArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = virtual_path(); if (_e) _o->virtual_path = _e->str(); }
  { auto _e = recursive(); _o->recursive = _e; }
  { auto _e = out_payload_ptr(); _o->out_payload_ptr = _e; }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<ListArgs> ListArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ListArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateListArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ListArgs> CreateListArgs(::flatbuffers::FlatBufferBuilder &_fbb, const ListArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ListArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _virtual_path = _o->virtual_path.empty() ? 0 : _fbb.CreateString(_o->virtual_path);
  auto _recursive = _o->recursive;
  auto _out_payload_ptr = _o->out_payload_ptr;
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::filesystem::CreateListArgs(
      _fbb,
      _virtual_path,
      _recursive,
      _out_payload_ptr,
      _out_result_ptr);
}

inline RemoveArgsT *RemoveArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RemoveArgsT>(new RemoveArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void RemoveArgs::UnPackTo(RemoveArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = virtual_path(); if (_e) _o->virtual_path = _e->str(); }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<RemoveArgs> RemoveArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RemoveArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateRemoveArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<RemoveArgs> CreateRemoveArgs(::flatbuffers::FlatBufferBuilder &_fbb, const RemoveArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const RemoveArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _virtual_path = _o->virtual_path.empty() ? 0 : _fbb.CreateString(_o->virtual_path);
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::filesystem::CreateRemoveArgs(
      _fbb,
      _virtual_path,
      _out_result_ptr);
}

inline MkdirArgsT *MkdirArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<MkdirArgsT>(new MkdirArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void MkdirArgs::UnPackTo(MkdirArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = virtual_path(); if (_e) _o->virtual_path = _e->str(); }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<MkdirArgs> MkdirArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MkdirArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMkdirArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<MkdirArgs> CreateMkdirArgs(::flatbuffers::FlatBufferBuilder &_fbb, const MkdirArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MkdirArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _virtual_path = _o->virtual_path.empty() ? 0 : _fbb.CreateString(_o->virtual_path);
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::filesystem::CreateMkdirArgs(
      _fbb,
      _virtual_path,
      _out_result_ptr);
}

inline RenameArgsT *RenameArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RenameArgsT>(new RenameArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void RenameArgs::UnPackTo(RenameArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = old_virtual_path(); if (_e) _o->old_virtual_path = _e->str(); }
  { auto _e = new_virtual_path(); if (_e) _o->new_virtual_path = _e->str(); }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<RenameArgs> RenameArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RenameArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateRenameArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<RenameArgs> CreateRenameArgs(::flatbuffers::FlatBufferBuilder &_fbb, const RenameArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const RenameArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _old_virtual_path = _o->old_virtual_path.empty() ? 0 : _fbb.CreateString(_o->old_virtual_path);
  auto _new_virtual_path = _o->new_virtual_path.empty() ? 0 : _fbb.CreateString(_o->new_virtual_path);
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::filesystem::CreateRenameArgs(
      _fbb,
      _old_virtual_path,
      _new_virtual_path,
      _out_result_ptr);
}

inline CopyArgsT *CopyArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CopyArgsT>(new CopyArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CopyArgs::UnPackTo(CopyArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = source_virtual_path(); if (_e) _o->source_virtual_path = _e->str(); }
  { auto _e = destination_virtual_path(); if (_e) _o->destination_virtual_path = _e->str(); }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<CopyArgs> CopyArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CopyArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCopyArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CopyArgs> CreateCopyArgs(::flatbuffers::FlatBufferBuilder &_fbb, const CopyArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CopyArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _source_virtual_path = _o->source_virtual_path.empty() ? 0 : _fbb.CreateString(_o->source_virtual_path);
  auto _destination_virtual_path = _o->destination_virtual_path.empty() ? 0 : _fbb.CreateString(_o->destination_virtual_path);
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::filesystem::CreateCopyArgs(
      _fbb,
      _source_virtual_path,
      _destination_virtual_path,
      _out_result_ptr);
}

inline MoveArgsT *MoveArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<MoveArgsT>(new MoveArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void MoveArgs::UnPackTo(MoveArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = source_virtual_path(); if (_e) _o->source_virtual_path = _e->str(); }
  { auto _e = destination_virtual_path(); if (_e) _o->destination_virtual_path = _e->str(); }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<MoveArgs> MoveArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MoveArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMoveArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<MoveArgs> CreateMoveArgs(::flatbuffers::FlatBufferBuilder &_fbb, const MoveArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MoveArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _source_virtual_path = _o->source_virtual_path.empty() ? 0 : _fbb.CreateString(_o->source_virtual_path);
  auto _destination_virtual_path = _o->destination_virtual_path.empty() ? 0 : _fbb.CreateString(_o->destination_virtual_path);
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::filesystem::CreateMoveArgs(
      _fbb,
      _source_virtual_path,
      _destination_virtual_path,
      _out_result_ptr);
}

inline StateArgsT *StateArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<StateArgsT>(new StateArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void StateArgs::UnPackTo(StateArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = virtual_path(); if (_e) _o->virtual_path = _e->str(); }
  { auto _e = out_payload_ptr(); _o->out_payload_ptr = _e; }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<StateArgs> StateArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const StateArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateStateArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<StateArgs> CreateStateArgs(::flatbuffers::FlatBufferBuilder &_fbb, const StateArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const StateArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _virtual_path = _o->virtual_path.empty() ? 0 : _fbb.CreateString(_o->virtual_path);
  auto _out_payload_ptr = _o->out_payload_ptr;
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::filesystem::CreateStateArgs(
      _fbb,
      _virtual_path,
      _out_payload_ptr,
      _out_result_ptr);
}

inline AbsoluteArgsT *AbsoluteArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<AbsoluteArgsT>(new AbsoluteArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void AbsoluteArgs::UnPackTo(AbsoluteArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = virtual_path(); if (_e) _o->virtual_path = _e->str(); }
  { auto _e = out_payload_ptr(); _o->out_payload_ptr = _e; }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<AbsoluteArgs> AbsoluteArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AbsoluteArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateAbsoluteArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<AbsoluteArgs> CreateAbsoluteArgs(::flatbuffers::FlatBufferBuilder &_fbb, const AbsoluteArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const AbsoluteArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _virtual_path = _o->virtual_path.empty() ? 0 : _fbb.CreateString(_o->virtual_path);
  auto _out_payload_ptr = _o->out_payload_ptr;
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::filesystem::CreateAbsoluteArgs(
      _fbb,
      _virtual_path,
      _out_payload_ptr,
      _out_result_ptr);
}

inline SetPropertyArgsT *SetPropertyArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SetPropertyArgsT>(new SetPropertyArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SetPropertyArgs::UnPackTo(SetPropertyArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = key(); if (_e) _o->key = _e->str(); }
  { auto _e = json_value(); if (_e) _o->json_value = _e->str(); }
}

inline ::flatbuffers::Offset<SetPropertyArgs> SetPropertyArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetPropertyArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSetPropertyArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SetPropertyArgs> CreateSetPropertyArgs(::flatbuffers::FlatBufferBuilder &_fbb, const SetPropertyArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SetPropertyArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _key = _o->key.empty() ? 0 : _fbb.CreateString(_o->key);
  auto _json_value = _o->json_value.empty() ? 0 : _fbb.CreateString(_o->json_value);
  return sandbox::schemas::filesystem::CreateSetPropertyArgs(
      _fbb,
      _key,
      _json_value);
}

inline GetPropertyArgsT *GetPropertyArgs::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<GetPropertyArgsT>(new GetPropertyArgsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void GetPropertyArgs::UnPackTo(GetPropertyArgsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = key(); if (_e) _o->key = _e->str(); }
  { auto _e = out_payload_ptr(); _o->out_payload_ptr = _e; }
  { auto _e = out_result_ptr(); _o->out_result_ptr = _e; }
}

inline ::flatbuffers::Offset<GetPropertyArgs> GetPropertyArgs::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GetPropertyArgsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateGetPropertyArgs(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<GetPropertyArgs> CreateGetPropertyArgs(::flatbuffers::FlatBufferBuilder &_fbb, const GetPropertyArgsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const GetPropertyArgsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _key = _o->key.empty() ? 0 : _fbb.CreateString(_o->key);
  auto _out_payload_ptr = _o->out_payload_ptr;
  auto _out_result_ptr = _o->out_result_ptr;
  return sandbox::schemas::filesystem::CreateGetPropertyArgs(
      _fbb,
      _key,
      _out_payload_ptr,
      _out_result_ptr);
}

}  // namespace filesystem
}  // namespace schemas
}  // namespace sandbox

#endif  // FLATBUFFERS_GENERATED_FILESYSTEM_SANDBOX_SCHEMAS_FILESYSTEM_H_
